- Cargo.toml
- crates/wasm-pkg-loader/src/package.rs
- crates/wkg/Cargo.toml
- crates/wkg/src/main.rs
- crates/wkg/src/package_spec.rs
```console
$ wkg get wasi:http
No version specified; fetching version list...
Getting wasi:http@0.2.0...
Wrote './wasi_http@0.2.0.wit'
$ wkg get --registry wow.wa.dev wow:claw@0.1.0
Getting wow:claw@0.1.0...
Wrote './wow_claw@0.1.0.wasm'
```
```console
$ wkg get --help
Get a package
Usage: wkg get [OPTIONS] <PACKAGE_SPEC>
Arguments:
<PACKAGE_SPEC>  The package to get, specified as <namespace>:<name> plus optional @<version>, e.g.
"wasi:cli" or "wasi:http@0.2.0"
Options:
-o, --output <OUTPUT>    Output path. If this ends with a '/', a filename based on the package
name, version, and format will be appended, e.g.
`name-space_name@1.0.0.wasm`` [default: ./]
--format <FORMAT>    Output format. The default of "auto" detects the format based on the
output filename or package contents [default: …
```
> Implement 'wkg get'

- crates/wasm-pkg-loader/src/source/oci.rs
- crates/wkg/src/main.rs
The docker_credential crate doesn't provide a ton of precision in its errors, so we'll downgrade all of its errors to a warning at worst to prevent unnecessary failures. This should remove an entire class of spurious failures at the expense of slightly harder debugging in certain cases.
Fixes #19
> oci: Make all docker credential errors non-fatal

- .github/workflows/publish-binaries.yml
- Cross.toml
After the following release, you can do:
`cargo install cargo-binstall` (if you don't have `cargo-binstall`)
`cargo binstall wkg` (which installs from binary artifacts built by the CI instead of building from source)
> add binary artifacts publishing for `cargo binstall`

- crates/wasm-pkg-loader/src/config.rs
- crates/wasm-pkg-loader/src/config/toml.rs
- crates/wasm-pkg-loader/src/source/oci.rs
- crates/wasm-pkg-loader/tests/e2e/src/main.rs
This is useful/required for local registries e.g.
```toml
default_registry = "localhost:5000"
[registry."localhost:5000"]
type = "oci"
protocol = "http"
```
> Support `protocol = "http"` in OCI registry config

- Cargo.lock
- Cargo.toml
- crates/wasm-pkg-loader/Cargo.toml
- crates/wkg/Cargo.toml
This PR disables the default features for the tracing-subscriber crate, primarily to avoid bringing in the [tracing-log](https://crates.io/crates/tracing-log) crate, which can introduce issues in downstream consumers because it attempts to init a global logger which may already be initialized (ref https://github.com/spinkube/containerd-shim-spin/issues/61).
If this project does have a need to utilize the tracing-log crate, we could also go an opt-out approach.
> ref(wasm-pkg-loader): turn default features off for tracing-subscriber crate

- crates/wasm-pkg-loader/src/config.rs
- crates/wasm-pkg-loader/src/lib.rs
- crates/wasm-pkg-loader/src/meta.rs
- crates/wasm-pkg-loader/src/source/local.rs
- crates/wasm-pkg-loader/src/source/oci.rs
- crates/wasm-pkg-loader/tests/e2e/Cargo.lock
- crates/wkg/src/main.rs
This is a small update to make sure we're following best practice and logging the values as fields
> ref(*): Switches all tracing macros to use fields

- CONTRIBUTING.md
- README.md
Nothing too fancy, this adds basic README and CONTRIBUTING files. These can be modified later to add more details as the project continues to be developed. Thanks!
> Add basic README and CONTRIBUTING files

- Cargo.lock
- Cargo.toml
I realized that wasm-pkg-loader was missing a bunch of useful re-exports.
This is basically a "usability bug fix", so just doing a patch release.
> Release 0.4.1

- Cargo.lock
- Cargo.toml
- crates/wasm-pkg-client/Cargo.toml
- crates/wasm-pkg-common/Cargo.toml
- crates/wkg/Cargo.toml
- crates/wkg/src/main.rs
- crates/wkg/src/oci.rs
This adds support for pushing and pulling compatible OCI wasm artifacts from the command line. As part of this refactor, it makes the original loading feature a separate command for use in debugging. Some of the features from the `load` subcommand should probably make their way into the push and pull command, but for now just keeping it simple
> feat(wkg)!: Adds support for pushing and pulling OCI wasm artifacts

- crates/wasm-pkg-client/src/caching/file.rs
- crates/wasm-pkg-client/src/caching/mod.rs
- crates/wasm-pkg-client/src/lib.rs
- crates/wasm-pkg-client/src/loader.rs
- crates/wasm-pkg-client/src/local.rs
- crates/wasm-pkg-client/src/oci/loader.rs
- crates/wasm-pkg-client/src/oci/mod.rs
- crates/wasm-pkg-client/src/warg/loader.rs
- crates/wasm-pkg-client/src/warg/mod.rs
- crates/wasm-pkg-client/tests/e2e/src/main.rs
- crates/wkg/src/main.rs
We now lock access to the sources through a RwLock instead
> feat(*)!: Makes client methods no longer require mut

- crates/wasm-pkg-common/src/config.rs
We take an owned config to create a client, which is probably the correct design. Because of this, we should probably have it clonable so it is easier to use.
I did run into this when adding this to cargo component. We might also want to make `Client` clonable down the line, but for now this should work
> feat(config): Adds `Clone` to the `Config` type

- Cargo.lock
- crates/wasm-pkg-client/Cargo.toml
- crates/wasm-pkg-client/src/oci/config.rs
- crates/wasm-pkg-client/src/warg/config.rs
- crates/wasm-pkg-client/src/warg/mod.rs
- crates/wasm-pkg-common/src/config.rs
- crates/wasm-pkg-common/src/config/toml.rs
Without these, it was basically impossible to serialize back to the intended config format expected
> fix(client): Implement various helpers for serialzing config structs

- crates/wasm-pkg-client/src/warg/mod.rs
The implementation for listing versions was pulling from the cache. This caused it to miss updates to versions when being used in cargo-component.
I discovered this while working on cargo-component and it was blocking tests from working
> fix(warg): Removes call to cache for versions

- crates/wasm-pkg-client/src/lib.rs
- crates/wasm-pkg-common/Cargo.toml
- crates/wasm-pkg-common/src/config.rs
- crates/wasm-pkg-common/src/config/toml.rs
This fixes an issue where if you have a single backend type set, you still would get a None backend type. This meant that unless you explicitly specified a type, it would always resolve to OCI as used by the client.
This takes a middle ground approach that lets people write less toml. If an explicit type is not specified and only one type of config exists for a registry, then the backend type of that single config will be used instead. For more than one, you must specify a default.
Please note that I renamed this from `type` to `default` as that term better expresses the intent of what this config is doing. A user isn't specifying the type of config so much as the default backend config to use here in the (currently) unlikely case you have a registry that talks more than one protocol
> fix(common): Fixes issue where we couldn't get a backend type

- crates/wasm-pkg-client/src/caching/mod.rs
This is needed so something that uses a client can check if it is in readonly mode or not
> feat(caching): Adds is_readonly method

- crates/wkg/Cargo.toml
This will clarify that [the wkg crates.io page] corresponds to this repository.
[the wkg crates.io page]: https://crates.io/crates/wkg
> Add a `repository` field to wkg's Cargo.toml.

- README.md
- crates/wasm-pkg-client/src/local.rs
- crates/wkg/src/main.rs
This should give people enough information to actually configure things properly on our first release. I also added a `--config` flag to `wkg` so that users can also manually specify a config file
> chore(docs): Adds documentation for configuration and repo

- crates/wasm-pkg-client/src/caching/mod.rs
I should have made this public in the first place. Also adds a helper method for turning a caching client back into a normal client
> fix(caching): Exposes methods for accessing the inner client

- Cargo.lock
- README.md
- crates/wasm-pkg-client/Cargo.toml
- crates/wasm-pkg-client/src/warg/config.rs
- crates/wasm-pkg-client/src/warg/mod.rs
- crates/wasm-pkg-client/src/warg/publisher.rs
Adds and documents a new option for adding a signing key for publishing. This should enable additional flexibility in setting a signing key for tools like `cargo component`
> feat(warg): Adds config option for signing secret

- .github/workflows/publish-binaries.yml
- Cargo.lock
- Cargo.toml
- crates/wasm-pkg-common/src/digest.rs
Also fixes a tiny warning that happened when the `tokio` feature was off.
> chore(*): Bumps version and adds a step for autopublishing crates

- crates/wasm-pkg-common/src/config.rs
- crates/wkg-core/tests/fixtures/cli-example/wit/world.wit
I also updated one of the integration tests to use the 0.2.1 interfaces
so we could make sure that works as well
> chore(common): Switches default registry to wasi.dev for wasi namespace

- README.md
- crates/wasm-pkg-client/src/lib.rs
- crates/wasm-pkg-client/src/oci/config.rs
- crates/wasm-pkg-client/src/warg/config.rs
- crates/wasm-pkg-client/tests/e2e.rs
- crates/wasm-pkg-common/src/config.rs
- crates/wasm-pkg-common/src/config/toml.rs
- crates/wasm-pkg-common/src/metadata.rs
- crates/wkg/src/main.rs
Adds support for an additional configuration for namespaces and packages so a well-known is not necessarily required
> feat(config): Adds additional configuration option for specifying metadata

- Cargo.lock
- Cargo.toml
- crates/wasm-pkg-client/src/lib.rs
If someone passes metadata for an override, we needed to use that instead
> fix(client): Fixes source resolution package overrides

- Cargo.lock
- Cargo.toml
- crates/wasm-pkg-core/src/resolver.rs
- crates/wasm-pkg-core/src/wit.rs
- crates/wasm-pkg-core/tests/fetch.rs
- crates/wasm-pkg-core/tests/fixtures/nested-local/local-dep/wit/world.wit
- crates/wasm-pkg-core/tests/fixtures/nested-local/project/wit/world.wit
When overriding with a local dependency, we weren't properly fetching nested dependencies. This fixes the issue. I bumped this to 0.8 because I ended up adding a helper method to the resolver
> fix(core): Make sure to fetch nested dependencies for local deps

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/wasm-pkg-client/Cargo.toml
- crates/wasm-pkg-client/src/oci/publisher.rs
- crates/wkg/Cargo.toml
- crates/wkg/tests/common.rs
- crates/wkg/tests/e2e.rs
- crates/wkg/tests/fixtures/wasi-http/.gitignore
- crates/wkg/tests/fixtures/wasi-http/wit/handler.wit
- crates/wkg/tests/fixtures/wasi-http/wit/proxy.wit
- crates/wkg/tests/fixtures/wasi-http/wit/types.wit
- crates/wkg/tests/fixtures/wasi-http/wkg.toml
This maps the metadata within a component (if it is present) to the appropriate annotations on the manifest. This also sets up some basic testing helpers for wkg e2e tests
> feat(client): Adds support for attaching annotations to manifests for OCI

- README.md
Also clarifies how wasm metadata is mapped to annotations
> docs: Adds documentation on wkg.toml and wkg.lock

- crates/wkg/src/main.rs
- crates/wkg/tests/e2e.rs
which compares the retrieved contents to an existing file, and exits with 0 if no difference or 1 if there is a difference.
I intend to use this in CI workflows much like https://github.com/bytecodealliance/wasmtime/blob/main/.github/workflows/main.yml#L508-L510
> add `--check` mode to `wkg get`

- Cargo.lock
- Cargo.toml
This brings in some [important improvements for `oci-client` from the recently released `v0.14.0`](https://github.com/oras-project/rust-oci-client/releases/tag/v0.14.0) along with the [recently tagged update to `oci-wasm` to bring it up to date with `oci-client`](https://github.com/bytecodealliance/rust-oci-wasm/releases/tag/v0.2.0) and bumps the versions to set this up for cutting a new tag.
> chore(deps): Update deps to use the latest OCI clients

- Cargo.lock
- crates/wasm-pkg-client/Cargo.toml
This pins `ptree` to 0.5.0 for consumers, addressing [GHSA-2326-pfpj-vx3h](https://github.com/advisories/GHSA-2326-pfpj-vx3h) and [RUSTSEC-2023-0086](https://rustsec.org/advisories/RUSTSEC-2023-0086.html).
> chore: bump warg-* 0.9.1

- Cargo.lock
Fixes [`RUSTSEC-2024-0402`](https://rustsec.org/advisories/RUSTSEC-2024-0402.html) / [`GHSA-wwq9-3cpr-mm53`](https://github.com/advisories/GHSA-wwq9-3cpr-mm53)
> fix: RUSTSEC-2024-0402

- Cargo.lock
- crates/wasm-pkg-core/src/resolver.rs
- crates/wasm-pkg-core/tests/fetch.rs
- crates/wasm-pkg-core/tests/fixtures/transitive-local/example-a/wit/world.wit
- crates/wasm-pkg-core/tests/fixtures/transitive-local/example-b/wit/world.wit
- crates/wasm-pkg-core/tests/fixtures/transitive-local/example-c/wit/world.wit
- crates/wkg/Cargo.toml
- **fix(core): use local override over registry dep**
- **test(core): add test for transitive local dep**
- **deps: enable tracing-subscriber ansi feature**
Fixes https://github.com/bytecodealliance/wasm-pkg-tools/issues/132
This PR:
1. Fixes an issue with transitive dependency fetching where a local dependency of a local dependency was treated as a registry dependency, which would fail
1. Adds a test for the above case to ensure that this works
1. Enables the `ansi` feature of tracing-subscriber so we can all have colored logging output <3
> fix(core): allow transitive fetching local deps

- crates/wkg/src/oci.rs
Closes #126 by enabling `wkg oci push` to print the digest after pushing. This enables us to make progress towards https://github.com/bytecodealliance/wkg-github-action/issues/6, which is needed for integrating with e.g. [actions/attest](https://github.com/actions/attest). Thanks!
```text
❯ cargo run --bin wkg oci push ghcr.io/yoshuawuyts/wasi/filesystem:0.2.0 ./webassembly_wasi_filesystem.wasm
pushed: ghcr.io/yoshuawuyts/wasi/filesystem:0.2.0
digest: sha256:1ef9132612ec97eb5bca4fed5a5177e8cb0c5ebabdb4cfa7e04a295386c05e4e
```
> print image digest from `wkg oci push`

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- crates/wasm-pkg-client/src/oci/publisher.rs
- crates/wasm-pkg-core/src/config.rs
- crates/wasm-pkg-core/src/lock.rs
- crates/wasm-pkg-core/src/wit.rs
- crates/wasm-pkg-core/tests/fixtures/cli-example/.cargo/config.toml
- crates/wasm-pkg-core/tests/fixtures/dog-fetcher/.cargo/config.toml
- crates/wkg/src/main.rs
- crates/wkg/tests/e2e.rs
- crates/wkg/tests/fixtures/wasi-http/wkg.toml
- BREAKING: Integrate upstream metadata overhaul. The set of fields available changed, meaning this may break some existing config files.
- Adapt to changed `WitPrinter` interface
- Update targets to `wasm32-wasip1`
> Upgrade wasm-tools to 0.224

- Cargo.lock
- Cargo.toml
- crates/wasm-pkg-core/src/resolver.rs
- crates/wasm-pkg-core/tests/build.rs
- crates/wasm-pkg-core/tests/fixtures/wasi-http/wit/handler.wit
- crates/wasm-pkg-core/tests/fixtures/wasi-http/wit/proxy.wit
- crates/wasm-pkg-core/tests/fixtures/wasi-http/wit/types.wit
Sets `Resolve::all_features = true` to avoid filtering out unstable features.
Added a test and manually verified by round-tripping `wasi:http@0.2.3` through `wkg publish/get`.
Fixes #143
> Include unstable features in published packages

- crates/wasm-pkg-client/src/oci/publisher.rs
Follow up to #146, this also allows the authors to be read from the wasm binary and written to the OCI package. Thanks!
> Add support for OCI authors annotation

- crates/wasm-pkg-common/Cargo.toml
- crates/wasm-pkg-common/src/metadata.rs
This commit adds support for specifying OCI namespace details on a `RegistryMetadata` and avoiding introducing the feature as a breaking change by utilizing an opt-in feature.
> feat: support specifying OCI namespace details on RegistryMetadata

- Cargo.lock
- Cargo.toml
- crates/wasm-pkg-core/src/wit.rs
Updated to wasm-tools 0.235 which included a breaking change to how `AddMetadata` is constructed.
> Bump version to 0.11
